### ISSUE TITLE
[BUG] weird icon on header when clicking logo

### ISSUE THREAD

**Issue by dewigman0801** [deltasig/sphinx#55]
**Describe the bug**
A weird icon appears by the logo when you click on ut

**To Reproduce**
1. Go to 'https://deltasig-de.org/sphinx'
2. Click on 'thw header'
3. See symbol by icon

**Expected behavior**
Weird symbol/icon doesn't appear

**Screenshots**
Failed to add. Will send to you

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: oneplus 6T
 - OS: OxygenOS 9.0.17
 - Browser chrome
 - Version 77.0.3865.116

**Additional context**

**Comment by tymorrow** [comment]
Fixed by c1b605d.
